/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubPathlessRouteImport } from './routes/sub/_pathless'
import { Route as SubPathlessIndexRouteImport } from './routes/sub/_pathless/index'

// Create Virtual Routes

const SubRouteImport = createFileRoute('/sub')()

// Create/Update Routes

const SubRoute = SubRouteImport.update({
  id: '/sub',
  path: '/sub',
  getParentRoute: () => rootRoute,
} as any)

const SubPathlessRoute = SubPathlessRouteImport.update({
  id: '/_pathless',
  getParentRoute: () => SubRoute,
} as any)

const SubPathlessIndexRoute = SubPathlessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubPathlessRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sub': {
      id: '/sub'
      path: '/sub'
      fullPath: '/sub'
      preLoaderRoute: typeof SubRouteImport
      parentRoute: typeof rootRoute
    }
    '/sub/_pathless': {
      id: '/sub/_pathless'
      path: '/sub'
      fullPath: '/sub'
      preLoaderRoute: typeof SubPathlessRouteImport
      parentRoute: typeof SubRoute
    }
    '/sub/_pathless/': {
      id: '/sub/_pathless/'
      path: '/'
      fullPath: '/sub/'
      preLoaderRoute: typeof SubPathlessIndexRouteImport
      parentRoute: typeof SubPathlessRouteImport
    }
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module './routes/sub/_pathless' {
  const createFileRoute: CreateFileRoute<
    '/sub/_pathless',
    FileRoutesByPath['/sub/_pathless']['parentRoute'],
    FileRoutesByPath['/sub/_pathless']['id'],
    FileRoutesByPath['/sub/_pathless']['path'],
    FileRoutesByPath['/sub/_pathless']['fullPath']
  >
}
declare module './routes/sub/_pathless/index' {
  const createFileRoute: CreateFileRoute<
    '/sub/_pathless/',
    FileRoutesByPath['/sub/_pathless/']['parentRoute'],
    FileRoutesByPath['/sub/_pathless/']['id'],
    FileRoutesByPath['/sub/_pathless/']['path'],
    FileRoutesByPath['/sub/_pathless/']['fullPath']
  >
}

// Create and export the route tree

interface SubPathlessRouteChildren {
  SubPathlessIndexRoute: typeof SubPathlessIndexRoute
}

const SubPathlessRouteChildren: SubPathlessRouteChildren = {
  SubPathlessIndexRoute: SubPathlessIndexRoute,
}

const SubPathlessRouteWithChildren = SubPathlessRoute._addFileChildren(
  SubPathlessRouteChildren,
)

interface SubRouteChildren {
  SubPathlessRoute: typeof SubPathlessRouteWithChildren
}

const SubRouteChildren: SubRouteChildren = {
  SubPathlessRoute: SubPathlessRouteWithChildren,
}

const SubRouteWithChildren = SubRoute._addFileChildren(SubRouteChildren)

export interface FileRoutesByFullPath {
  '/sub': typeof SubPathlessRouteWithChildren
  '/sub/': typeof SubPathlessIndexRoute
}

export interface FileRoutesByTo {
  '/sub': typeof SubPathlessIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/sub': typeof SubRouteWithChildren
  '/sub/_pathless': typeof SubPathlessRouteWithChildren
  '/sub/_pathless/': typeof SubPathlessIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sub' | '/sub/'
  fileRoutesByTo: FileRoutesByTo
  to: '/sub'
  id: '__root__' | '/sub' | '/sub/_pathless' | '/sub/_pathless/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SubRoute: typeof SubRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  SubRoute: SubRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/sub"
      ]
    },
    "/sub": {
      "filePath": "sub",
      "children": [
        "/sub/_pathless"
      ]
    },
    "/sub/_pathless": {
      "filePath": "sub/_pathless.tsx",
      "parent": "/sub",
      "children": [
        "/sub/_pathless/"
      ]
    },
    "/sub/_pathless/": {
      "filePath": "sub/_pathless/index.tsx",
      "parent": "/sub/_pathless"
    }
  }
}
ROUTE_MANIFEST_END */
